### ISSUE TITLE
How to support react-native?

### ISSUE THREAD

**Issue by joonhocho** [relay-tools/react-router-relay#111]
I am trying to use Relay for both React and React Native and wonder if react-router-relay could be used for react-native as well in the future.
I haven't dug into the source code yet, but how much does react-router-relay depend on browser specific APIs?
react-native exposes their new Navigation APIs here [NavigationExperimental](https://github.com/facebook/react-native/tree/master/Libraries/NavigationExperimental).
I am going to be digging into source codes, but could authors of react-router-relay share some gotchas for routing with relay?

**Comment by taion** [comment]
We've decided at length that we do not recommend React Router style APIs for working with React Native in the general case. We do not currently use React Router for React Native development, and do not plan to do so at any point in the future.

As such, I don't plan on adding support for React Native either here or in React Router, because I don't think it's the right pattern, and because I don't plan on setting up my React Native navigation in that manner. Just use a `<RootContainer>` per scene.

You can find more details on https://github.com/reactjs/react-router/issues/743#issuecomment-175815329.

cc @skevy

**Comment by CoericK** [comment]
Hey @taion, went into the same question, is this still the recommended way to work, crea a RootContainer per scene?

**Comment by taion** [comment]
It might work with react-router-native? cc @jmurzy

We don't handle our RN navigation using that sort of approach, so we've just been doing per-scene renderers.

**Comment by Lenin7** [comment]
@jmurzy?

**Comment by Lenin7** [comment]
Does anyone have an example of per-scene renderers with relay?

**Comment by joonhocho** [comment]
@Lenin7 https://github.com/joonhocho/react-native-router-relay-todo Here's an example how I am using `relay` with `react-router-native`. It needs some tweaks to react-router-native, but it works for me.
I am currently not touching any navigation stuff, so it may be out of date, but you will get the idea.
