### ISSUE TITLE
Reconsider switch to rrtr

### ISSUE THREAD

**Issue by mattecapu** [relay-tools/react-router-relay#119]
I don't want to make an ad-hoc argument, but a lot of the Relay isomorphic stack builds on both this package and `react-router`, switching to `rrtr` splits all the dependencies and adds up to the bundle size.

I would suggest to fork this package too to `rrtr-relay` to better reflect its stack assumptions and to avoid locking out people who want to stick with `react-router`.

Just to clarify, this should be independent from any reason that brought to the fork.

**Comment by mattecapu** [comment]
I was actually wrong on the splitting deps & increases bundle size thing, but it still feels unfair to publish the package as `react-router-*`

**Comment by mattecapu** [comment]
Packages which lists both  `react-router` and `react-router-relay` among their dependencies:

* [`isomorphic-relay-router`](https://github.com/denvned/isomorphic-relay-router/blob/master/package.json#L51)
* [`relay-fullstack`](https://github.com/lvarayut/relay-fullstack/blob/master/package.json#L79)
* [`codepix-client`](https://www.npmjs.com/package/codepix-client)
* [`koa-isomorphic-relay`](https://github.com/DanielHuisman/koa-isomorphic-relay/blob/master/package.json#L25)

They're not a lot nor very popular, but **they are 100% of the npm packages which depend on `react-router-relay`**.

**Comment by taion** [comment]
I'm surprised the packages even work together. I'm getting the same complaint on React-Router-Bootstrap. Obviously my first choice would be for the dependents to point to rrtr, but give me a bit of time to figure out what to do here.

**Comment by nodkz** [comment]
Matteo, good thoughts! I think it would be great to not break existing
ecosystem of packages and projects.

Jimmy, do you remember couple of weeks ago somebody kill package, which
break babel install. Or btw somebody yesterday say about changing api to
often...

I think it would be great, if u leave your relay packages with react-router
and community will be happy. And for rrtr create new one.

@denvned what do u think?
13 апр. 2016 г. 2:13 AM пользователь "Jimmy Jia" <notifications@github.com>
написал:

I'm surprised the packages even work together. I'm getting the same
complaint on React-Router-Bootstrap. Obviously my first choice would be for
the dependents to point to rrtr, but give me a bit of time to figure out
what to do here.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/relay-tools/react-router-relay/issues/119#issuecomment-209084526>

**Comment by taion** [comment]
fixed
