### ISSUE TITLE
Umbrella 1.0

### ISSUE THREAD

**Issue by devknoll** [relay-tools/react-router-relay#19]
- [ ] Flow types
- [x] Jests
- [x] react-router 1.0

**Comment by taion** [comment]
Last one is done, assuming `rc1` is the near-final API.

**Comment by taion** [comment]
Well, I sort of have a bit of test coverage. I ended up not using Jest for now because I just wanted to get some confidence that my Router v2 changes aren't breaking the world. The test coverage is a stub that I'm not too attached to, though.

I'm going to close this for now, since we're tracking Flow annotations separately on https://github.com/relay-tools/react-router-relay/issues/11.
