### ISSUE TITLE
Route props as query variables

### ISSUE THREAD

**Issue by emilsjolander** [relay-tools/react-router-relay#58]
It does not seem to currently be possible to assign a relay query with parameters outside of those in the url (path and query string params). Is there any interest in being able to pass these variables down via properties on the route?

My reason for this is to pass auth data to a query without having it be part of the url. What i would like to have is something like the following.

```js
<Route path="profile"
    component={Profile}
    queries={userQuery}
    authData={authData}/> 
```

If this is something that others would like to have as well i would be more than happy to open a pull request with this addition. Please tell me if there are better ways to achieve similar results.

**Comment by taion** [comment]
Right now I'd use `stateParams` to do this, or set this up in `prepareVariables` in the containers that have default parameters (assuming you're not doing this on the root query).

**Comment by emilsjolander** [comment]
I am doing this in the root query actually.

**Comment by taion** [comment]
How about `stateParams`, then? I feel like it'd just be cleaner to have all params be a function of something related to the current route/history frame.

**Comment by emilsjolander** [comment]
I will look back at stateParams. I think i might have misunderstood their use. Thank you.

**Comment by emilsjolander** [comment]
Please tell me if this is the wrong forum for a question like this but i am having trouble getting stateParams to function as a good alternative.

I have an `App` component which renders a router depending on the signed in state of the user.
```js
class App extends React.Component {
  render() {
    if (authData) {
       <Router history={history} createElement={ReactRouterRelay.createElement}>
         <Route ...../>
       </Router>
    } else {
      <Router history={history} createElement={ReactRouterRelay.createElement}>
         <Route ...../>
       </Router>
    }
  }
}
```
The routes contained in the router will depend on a `meQuery` which requires the `authData` variable. Can stateParams solve this issue or will some re-structuring be needed to work within the current confines of this library?

**Comment by taion** [comment]
With `stateParams` the idea would be that you `history.setState` the auth data before you hit your route.

I'll have to think about this a bit otherwise. My approach with auth doesn't look like this - I just inject the auth headers with my network layer rather than having them be part of the GraphQL query itself.

**Comment by emilsjolander** [comment]
I did finally get something working with modifying the state on the history in the onEnter callback. It's not the prettiest of solutions but it works for now. I might drop in a pull request later if i end up modifying the library to better suite my needs.

**Comment by emilsjolander** [comment]
Thanks for the help.

**Comment by taion** [comment]
BTW, I'd recommend against handling auth this way. You should instead use the `Authorization` HTTP header. This has a few advantages:

- It better preserves HTTP semantics
- In many cases, it's easier to load the auth information onto `rootValue` from headers when handling the request
- Even if your initial query is of the form `query { viewer(auth: $auth) { foo } }`, if Relay decides to re-fetch something, it will issue queries of the form `query { node(id: $id) { whatever } }`, i.e. you will lose the auth information from your original root query

**Comment by emilsjolander** [comment]
Ok, thanks for the input. I'll look into re-working my auth setup.

**Comment by ianstormtaylor** [comment]
Running into this as well. It's not so much that I'm handling authentication via the GraphQL query, but that the logged-in user's `ID` is stored in a cookie, (as part of being authenticated with the web server), so that you can render routes without needing their `:userId` in the URL. (Exactly how GitHub's or Twitter's or whoever's homepage works.)

The authentication itself happens via HTTP headers, but which `userId` to fetch is read from the cookie. This seems to make perfect sense, or else I'd have to somehow create a new GraphQL resource or resolver that got the logged-in user?

@taion what would you recommend here? It seems like if I really wanted to not need to pass in a `userId`, I'd need to allow for my GraphQL server to handle something like:

```
query {
  user(id: "SOMEID") {
    ...
  }
}
```

Or to handle:

```
query {
  user(auth: true) {

  }
}
```

But that would be made even more complex if the webserver itself was just a thin layer that rendered the frontend, and the API was actually handled by a different service. The webserver would need to parse and restringify the query to transform that `auth: true` bit?

Curious to know if that makes sense, or if I'm forgetting something, and how you'd handle this case. It seems pretty common.

**Comment by taion** [comment]
You could use `prepareParams`.

My interpretation of the examples is that `viewer` does typically refer to the current logged-in user, though.
