### ISSUE TITLE
Use custom Relay root renderer

### ISSUE THREAD

**Issue by taion** [relay-tools/react-router-relay#68]
Per @josephsavona on https://github.com/facebook/relay/issues/496#issuecomment-151805843.

Using one per route means I can have multiple active Relay routes at the same time, which better optimizes re-rendering.

**Comment by taion** [comment]
Oops, didn't mean to close this. Sorry!

**Comment by skevy** [comment]
:)

**Comment by skosch** [comment]
This feature would be great to have (if I understand correctly what it would do).

I used to have a `<Layout>{this.props.children}</Layout>` component on my `/` route, and the child routes would fill in the actual content. But with Relay, the only way to make that work (without re-rendering on location change) is to give the child routes not only the same `<Layout>` parent, but also to have them share the same query root (`viewer`, or whatever you'd like to call it). I would much rather have individual queries for every route, so that their data only gets downloaded once the user navigates to them. (Do correct me if this is already achievable, and I'm just doing it wrong.)

**Comment by taion** [comment]
Queries are per-route. That's the whole point of this library. This issue doesn't really touch on any of those; it'd mostly be a minor internal optimization.

**Comment by skosch** [comment]
Thanks @taion. On re-reading my question, it wasn't clear what the problem was – the intermediate `<Layout>` has to pass down/query up different data depending on which child is currently shown. It's very similar to #93, so disregard my comment here.

**Comment by taion** [comment]
This is warning now on newer versions of Relay. Looks like the big thing is that I need to fork https://github.com/facebook/relay/blob/master/src/container/getRelayQueries.js.

**Comment by taion** [comment]
Never mind, that was a bug in my code.

For my own benefit, this issue is more about avoiding re-generating the `route` context at each level.

**Comment by taion** [comment]
I went with this approach in found-relay: https://github.com/4Catalyzer/found-relay/pull/1, which does set up separate renderers for each Relay route, and enables per-route `forceFetch`.

I don't currently plan on backporting that implementation here, so I'm going to close this issue for now.
