### ISSUE TITLE
renderFailure on subroute

### ISSUE THREAD

**Issue by quazzie** [relay-tools/react-router-relay#91]
I renderFailure never gets called on a subroute. Say i have this:

```
<Route path="/" queries={rootqueries}>
  <Route path="/test" queries={testqueries} renderFailure={err => <div>Error</div>} />
</Route>
```

if testqueries fails with this response:
```
{
  data: { testdata: null },
  errors: [{ message: 'Test error', locations: [{ line: 1, column: 14}] }]
}
```

it thinks data fetched ok and tries to render normally.

**Comment by taion** [comment]
Failures aren't localized to routes – so it's actually failing to render the parent in your case, if this is on a fresh page load.

**Comment by filod** [comment]
@taion  will failures to be localized in future releases ?

**Comment by taion** [comment]
Maybe? Who knows.

**Comment by rojobuffalo** [comment]
In case anyone else is unclear about what this means, @taion mentioned in Reactiflux#relay
> global 404ing in react router based on missing data is more or less impossible

So the way I'm dealing with this problem is to delegate missing data handling to the container. You could use a lifecycle method to check if data is missing and return a different component or re-route to a different component, such as a 404 page. If your container is a stateless component, you can do something like:
```
const ProjectContainer = (props, context) => (!props.project
  ? <NotFoundPage message={'Project not found.'} />
  : <TransitionWrapper>
    <div className={classNames.this}>
      ...
```
